---
- name: Configure Kubernetes Nodes
  become: True
  hosts: nodes
  gather_facts: no
  vars_files:
    - defaults/main.yaml
  remote_user: "{{ username }}"
  tasks:
    
    - name: Configure nodes
      ansible.builtin.include_tasks:
        file: tasks/configure_nodes.yml
    
    - name: Configure first Control Plane and Etcd node
      ansible.builtin.include_tasks:
        file: tasks/configure_control_plane.yml
      when: inventory_hostname in groups['control_plane']
    
    - name: Configure Workers nodes
      ansible.builtin.include_tasks:
        file: tasks/join_workers.yml
      when: "'workers' in group_names"    

    - name: Install features
      ansible.builtin.include_tasks:
        file: tasks/install_features.yml
      when: 
        - groups['control_plane'][0] == inventory_hostname
      with_items: "{{ feature }}"